### ISSUE TITLE
Click machine has class loading errors

### ISSUE THREAD

**Issue by ImAzurea** [Shadows-of-Fire/ClickMachine#47]
Im new to crashes and crash fixing as previously I just got rid of mods that caused errors, but id really like to run this one but it crashes on startup giving the quoted error. 

"org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered" 

[crash-2022-08-17_16.46.56-fml.txt](https://github.com/Shadows-of-Fire/ClickMachine/files/9366663/crash-2022-08-17_16.46.56-fml.txt)

**Comment by Shadows-of-Fire** [comment]
`	Caused by 1: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [assets/the_vault/the_vault.mixins.json:MixinSlotItemHandler] from phase [DEFAULT] in config [assets/the_vault/the_vault.mixins.json] FAILED during APPLY`

Not sure why clickmachine is in the stacktrace (I guess thats just the trace of the classload process), but it's vault's mixin failing.  You'll have to take it up with them.
